import scrapy


class ObamaWhiteHouseHarvestListSpider(scrapy.Spider):
    name = "obama_whitehouse_harvest_list"
    allowed_domains = ["obamawhitehouse.archives.gov"]

    # Hardcoded rather than taken via -a: this is a static archived site, so
    # the true set of listing pages never changes. Add newly-discovered
    # listing candidates (from the nav harvester's is_listing=True output,
    # reviewed) directly here and push, rather than building a dynamic
    # seeds-file mechanism.
    start_urls = [
        "https://obamawhitehouse.archives.gov/briefing-room/speeches-and-remarks",
        "https://obamawhitehouse.archives.gov/briefing-room/press-briefings",
        "https://obamawhitehouse.archives.gov/briefing-room/statements-and-releases",
        "https://obamawhitehouse.archives.gov/briefing-room/presidential-actions",
        "https://obamawhitehouse.archives.gov/briefing-room/weekly-address",
        "https://obamawhitehouse.archives.gov/blog",
        # Discovered via the nav harvester's is_listing=True flagging
        # (2026-07-25 runs), reviewed and confirmed as real listings.
        "https://obamawhitehouse.archives.gov/administration/eop/cea/blog",
        "https://obamawhitehouse.archives.gov/administration/eop/ceq/blog",
        "https://obamawhitehouse.archives.gov/administration/eop/ceq/press_releases",
        "https://obamawhitehouse.archives.gov/administration/eop/cwg/blog",
        "https://obamawhitehouse.archives.gov/administration/eop/iga/blog",
        "https://obamawhitehouse.archives.gov/administration/eop/ofbnp/blog",
        "https://obamawhitehouse.archives.gov/administration/eop/ope/blog",
        "https://obamawhitehouse.archives.gov/administration/eop/ostp/blog",
        "https://obamawhitehouse.archives.gov/administration/eop/ostp/pressroom",
        "https://obamawhitehouse.archives.gov/administration/eop/oua/blog",
        "https://obamawhitehouse.archives.gov/administration/eop/oua/press",
        "https://obamawhitehouse.archives.gov/administration/eop/sicp/blog",
        "https://obamawhitehouse.archives.gov/blog/author/Shaun-Donovan",
        "https://obamawhitehouse.archives.gov/blog/author/adam-garber",
        "https://obamawhitehouse.archives.gov/blog/author/ali-zaidi",
        "https://obamawhitehouse.archives.gov/blog/author/amy-dudley",
        "https://obamawhitehouse.archives.gov/blog/author/aneesh-chopra",
        "https://obamawhitehouse.archives.gov/blog/author/ben-rhodes",
        "https://obamawhitehouse.archives.gov/blog/author/brian-deese",
        "https://obamawhitehouse.archives.gov/blog/author/brian-levine",
        "https://obamawhitehouse.archives.gov/blog/author/broderick-johnson",
        "https://obamawhitehouse.archives.gov/blog/author/carrie-bettinger-lopez",
        "https://obamawhitehouse.archives.gov/blog/author/cecilia-mu%C3%B1oz",
        "https://obamawhitehouse.archives.gov/blog/author/charlie-anderson",
        "https://obamawhitehouse.archives.gov/blog/author/colleen-curtis",
        "https://obamawhitehouse.archives.gov/blog/author/craig-fugate",
        "https://obamawhitehouse.archives.gov/blog/author/dan-utech",
        "https://obamawhitehouse.archives.gov/blog/author/danny-werfel",
        "https://obamawhitehouse.archives.gov/blog/author/david-vandivier",
        "https://obamawhitehouse.archives.gov/blog/author/david-wilkinson",
        "https://obamawhitehouse.archives.gov/blog/author/derek-douglas",
        "https://obamawhitehouse.archives.gov/blog/author/dj-patil",
        "https://obamawhitehouse.archives.gov/blog/author/doug-rand",
        "https://obamawhitehouse.archives.gov/blog/author/dr-jill-biden",
        "https://obamawhitehouse.archives.gov/blog/author/elizabeth-alexander",
        "https://obamawhitehouse.archives.gov/blog/author/eric-waldo",
        "https://obamawhitehouse.archives.gov/blog/author/felicia-escobar",
        "https://obamawhitehouse.archives.gov/blog/author/first-lady-michelle-obama",
        "https://obamawhitehouse.archives.gov/blog/author/gayle-smith",
        "https://obamawhitehouse.archives.gov/blog/author/gina-mccarthy",
        "https://obamawhitehouse.archives.gov/blog/author/grant-t-harris",
        "https://obamawhitehouse.archives.gov/blog/author/greg-nelson",
        "https://obamawhitehouse.archives.gov/blog/author/hope-hall",
        "https://obamawhitehouse.archives.gov/blog/author/howard-schmidt",
        "https://obamawhitehouse.archives.gov/blog/author/jack-lew",
        "https://obamawhitehouse.archives.gov/blog/author/jared-bernstein",
        "https://obamawhitehouse.archives.gov/blog/author/jason-furman",
        "https://obamawhitehouse.archives.gov/blog/author/jeffrey-zients",
        "https://obamawhitehouse.archives.gov/blog/author/jennifer-erickson",
        "https://obamawhitehouse.archives.gov/blog/author/jennifer-palmieri",
        "https://obamawhitehouse.archives.gov/blog/author/jerry-abramson",
        "https://obamawhitehouse.archives.gov/blog/author/jesse-lee",
        "https://obamawhitehouse.archives.gov/blog/author/joshua-miller",
        "https://obamawhitehouse.archives.gov/blog/author/julie-chavez-rodriguez",
        "https://obamawhitehouse.archives.gov/blog/author/kori-schulman",
        "https://obamawhitehouse.archives.gov/blog/author/kristin-lee",
        "https://obamawhitehouse.archives.gov/blog/author/kyle-lierman",
        "https://obamawhitehouse.archives.gov/blog/author/laura-miller",
        "https://obamawhitehouse.archives.gov/blog/author/lauren-kelly",
        "https://obamawhitehouse.archives.gov/blog/author/lindsay-holst",
        "https://obamawhitehouse.archives.gov/blog/author/lisa-o-monaco",
        "https://obamawhitehouse.archives.gov/blog/author/liz-oxhorn",
        "https://obamawhitehouse.archives.gov/blog/author/lloyd-whitman",
        "https://obamawhitehouse.archives.gov/blog/author/macon-phillips",
        "https://obamawhitehouse.archives.gov/blog/author/matt-compton",
        "https://obamawhitehouse.archives.gov/blog/author/maureen-tracey-mooney",
        "https://obamawhitehouse.archives.gov/blog/author/megan-slack",
        "https://obamawhitehouse.archives.gov/blog/author/megan-smith",
        "https://obamawhitehouse.archives.gov/blog/author/michael-botticelli",
        "https://obamawhitehouse.archives.gov/blog/author/monique-dorsainvil",
        "https://obamawhitehouse.archives.gov/blog/author/pete-souza",
        "https://obamawhitehouse.archives.gov/blog/author/president-barack-obama",
        "https://obamawhitehouse.archives.gov/blog/author/r-david-edelman",
        "https://obamawhitehouse.archives.gov/blog/author/rachel-kopilow",
        "https://obamawhitehouse.archives.gov/blog/author/rick-weiss",
        "https://obamawhitehouse.archives.gov/blog/author/roberto-j-rodr%C3%ADguez",
        "https://obamawhitehouse.archives.gov/blog/author/samantha-power",
        "https://obamawhitehouse.archives.gov/blog/author/secretary-anthony-foxx",
        "https://obamawhitehouse.archives.gov/blog/author/secretary-arne-duncan",
        "https://obamawhitehouse.archives.gov/blog/author/secretary-ernest-moniz",
        "https://obamawhitehouse.archives.gov/blog/author/secretary-penny-pritzker",
        "https://obamawhitehouse.archives.gov/blog/author/secretary-ray-lahood",
        "https://obamawhitehouse.archives.gov/blog/author/secretary-steven-chu",
        "https://obamawhitehouse.archives.gov/blog/author/secretary-sylvia-mathews-burwell",
        "https://obamawhitehouse.archives.gov/blog/author/secretary-thomas-e-perez",
        "https://obamawhitehouse.archives.gov/blog/author/secretary-tom-vilsack",
        "https://obamawhitehouse.archives.gov/blog/author/simone-leiro",
        "https://obamawhitehouse.archives.gov/blog/author/steve-vanroekel",
        "https://obamawhitehouse.archives.gov/blog/author/terrell-mcsweeny",
        "https://obamawhitehouse.archives.gov/blog/author/thomas-kalil",
        "https://obamawhitehouse.archives.gov/blog/author/tobin-marcus",
        "https://obamawhitehouse.archives.gov/blog/author/todd-park",
        "https://obamawhitehouse.archives.gov/blog/author/valerie-jarrett",
        "https://obamawhitehouse.archives.gov/blog/author/victoria-espinel",
        "https://obamawhitehouse.archives.gov/champions/blog",
        "https://obamawhitehouse.archives.gov/economy/business/startup-america",
        "https://obamawhitehouse.archives.gov/economy/business/startup-america/commitments",
        "https://obamawhitehouse.archives.gov/economy/business/startup-america/contact",
        "https://obamawhitehouse.archives.gov/economy/business/startup-america/progress-report",
        "https://obamawhitehouse.archives.gov/economy/jobs/news",
        "https://obamawhitehouse.archives.gov/economy/jobsact",
        "https://obamawhitehouse.archives.gov/goodgovernment/news",
        "https://obamawhitehouse.archives.gov/issues/education/k-12/connected",
        "https://obamawhitehouse.archives.gov/issues/education/k-12/race-to-the-top",
        "https://obamawhitehouse.archives.gov/jobsact/read-the-bill",
        "https://obamawhitehouse.archives.gov/joiningforces/blog",
        "https://obamawhitehouse.archives.gov/omb/blog",
        "https://obamawhitehouse.archives.gov/ondcp/blog",
        "https://obamawhitehouse.archives.gov/open/blog",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/august-2016-photo-day",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/december-2016-photo-day",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/january-2017-photo-day",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/july-2016-photo-day",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/june-2016-photo-day",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/november-2016-photo-day",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/october-2016-photo-day",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/september-2016-photo-day",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/vice-president-and-dr-biden-middle-east",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/vice-president-and-dr-bidens-trip-india-and-singapore",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/vice-president-biden-spain-and-belgium-1",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/vice-president-biden-visits-afghanistan-pakistan-and-iraq",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/vice-president-joe-biden-tk",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/vice-president-joe-biden-turkey/index__q_category=30.html",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/vice-presidents-trip-asia",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2010/12/08/open-questions-first-anniversary-open-government-directive",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2011/06/13/building-21st-century-grid",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2011/12/21/pcast-december-conference-call",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2012/03/27/president-obama-speaks-nuclear-security-summit",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2012/04/26/pcast-april-conference-call",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2013/05/09/president-obama-speaks-innovation-and-manufacturing",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2013/05/09/president-obama-speaks-manor-new-technology-high-school",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2013/06/06/president-obama-speaks-technology-schools",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2013/12/13/west-wing-week-121313-or-madiba-farewell",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2013/12/18/board-travels-vice-president-asia",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2014/02/04/president-obama-speaks-connected",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2014/07/08/road-drc-dr-mukwege-panzi-hospital",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2014/07/19/equipping-workers-skills-employers-need-now-and-future",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2014/07/23/white-house-white-board-vice-president-biden-rebuild-america",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2014/08/20/introducing-us-digital-service",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2014/11/14/west-wing-week-111414-or-future-we-see",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2015/01/28/board-kal-penn-travels-president-obama-india",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2015/02/13/president-obama-speaks-cybersecurity-and-consumer-protection-summi",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2015/02/18/president-obama-speaks-summit-countering-violent-extremism",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2015/02/19/president-obama-speaks-summit-countering-violent-extremism",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2015/03/23/president-obama-delivers-message-nigerian-people",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2015/04/17/tech-meetup-white-house",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2015/05/08/west-wing-week-05082015-or-viva-los-estados-unidos",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2015/05/18/president-speaks-youth-and-law-enforcement-new-jersey",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2015/05/22/west-wing-week-05222015-or-potus",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2015/08/15/continuing-work-improve-community-policing",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2015/12/06/president-addresses-nation-keeping-american-people-safe",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2015/12/17/president-speaks-national-counterterrorism-center",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2016/04/01/potus-nuclear-security-summit-press-conference",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2016/04/01/president-obama-chairs-closing-session-nuclear-summit",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2016/04/01/president-obama-meets-members-p5-plus-1",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2016/06/13/white-house-organ-summit",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2016/09/08/first-lady-michelle-obama-honors-2016-class-national-student-poets",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2016/09/21/president-obama-delivers-remarks-us-africa-business-forum",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2016/10/17/president-obama-delivers-remarks-education",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2016/12/21/white-house-summit-building-tech-workforce-tomorrow",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2017/01/12/organizational-transformation-symposium",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2017/01/13/11317-white-house-press-briefing",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2017/01/13/healthy-campus-challenge-day-white-house",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2017/01/14/weekly-address-honor-serving-you-president",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2017/01/16/2016-world-series-champion-chicago-cubs",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2017/01/16/participating-service-project-martin-luther-king-jr-day",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2017/01/17/11717-white-house-press-briefing",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/forum-modernizing-government-closing-session",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/forum-modernizing-government-maximizing-technology-return-investment",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/forum-modernizing-government-opening-session",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/forum-modernizing-government-streamlining-operations-1",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/forum-modernizing-government-streamlining-operations-2",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/forum-modernizing-government-transforming-customer-service-1",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/forum-modernizing-government-transforming-customer-service-2",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/limiting-influence-special-interests",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/open-questions-sustainable-communities",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/recovery-act-tax-savings-tool",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/tax-accountability-government-contracts",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/vice-president-biden-speaks-kenya",
        "https://obamawhitehouse.archives.gov/recovery/blog",
        "https://obamawhitehouse.archives.gov/strongmiddleclass/blog",
        "https://obamawhitehouse.archives.gov/video/President-Obama-Speaks-to-the-Muslim-World-from-Cairo-Egypt",
        "https://obamawhitehouse.archives.gov/video/President-Obama-on-Urban-Policy",
    ]

    def parse(self, response):
        # Two known listing templates: teaser-card (.views-row, e.g. blog/
        # author pages) and table-based gallery (.views-field-title, e.g.
        # photo/video galleries). Try the first, fall back to the second.
        links = response.css(
            '.views-row h2 a::attr(href), .views-row h3 a::attr(href)'
        ).getall()
        if not links:
            links = response.css('.views-field-title a::attr(href)').getall()
        if not links:
            return

        for href in links:
            yield {'url': response.urljoin(href)}

        # .pager-current's immediately-following sibling <li> holds the
        # forward link in both templates (a "Next" link in the teaser-card
        # pager, a numbered page link in the gallery pager) - confirmed
        # empirically on both, so one selector covers both rather than
        # branching on .pager-next (which the gallery template doesn't use
        # at all).
        next_page = response.css('.pager-current + li a::attr(href)').get()
        if next_page:
            yield response.follow(next_page, callback=self.parse)
