import scrapy


class ObamaWhiteHouseHarvestListSpider(scrapy.Spider):
    name = "obama_whitehouse_harvest_list"
    allowed_domains = ["obamawhitehouse.archives.gov"]

    # Hardcoded rather than taken via -a: this is a static archived site, so
    # the true set of listing pages never changes. Add newly-discovered
    # listing candidates (from the nav harvester's is_listing=True output,
    # reviewed) directly here and push, rather than building a dynamic
    # seeds-file mechanism.
    start_urls = [
        "https://obamawhitehouse.archives.gov/briefing-room/speeches-and-remarks",
        "https://obamawhitehouse.archives.gov/briefing-room/press-briefings",
        "https://obamawhitehouse.archives.gov/briefing-room/statements-and-releases",
        "https://obamawhitehouse.archives.gov/briefing-room/presidential-actions",
        "https://obamawhitehouse.archives.gov/briefing-room/weekly-address",
        "https://obamawhitehouse.archives.gov/blog",
        # Discovered via the nav harvester's is_listing=True flagging
        # (2026-07-25 runs), reviewed and confirmed as real listings.
        "https://obamawhitehouse.archives.gov/administration/eop/cea/blog",
        "https://obamawhitehouse.archives.gov/administration/eop/ceq/blog",
        "https://obamawhitehouse.archives.gov/administration/eop/ceq/press_releases",
        "https://obamawhitehouse.archives.gov/administration/eop/cwg/blog",
        "https://obamawhitehouse.archives.gov/administration/eop/iga/blog",
        "https://obamawhitehouse.archives.gov/administration/eop/ofbnp/blog",
        "https://obamawhitehouse.archives.gov/administration/eop/ope/blog",
        "https://obamawhitehouse.archives.gov/administration/eop/ostp/blog",
        "https://obamawhitehouse.archives.gov/administration/eop/ostp/pressroom",
        "https://obamawhitehouse.archives.gov/administration/eop/oua/blog",
        "https://obamawhitehouse.archives.gov/administration/eop/oua/press",
        "https://obamawhitehouse.archives.gov/administration/eop/sicp/blog",
        "https://obamawhitehouse.archives.gov/blog/author/Shaun-Donovan",
        "https://obamawhitehouse.archives.gov/blog/author/adam-garber",
        "https://obamawhitehouse.archives.gov/blog/author/ali-zaidi",
        "https://obamawhitehouse.archives.gov/blog/author/amy-dudley",
        "https://obamawhitehouse.archives.gov/blog/author/aneesh-chopra",
        "https://obamawhitehouse.archives.gov/blog/author/ben-rhodes",
        "https://obamawhitehouse.archives.gov/blog/author/brian-deese",
        "https://obamawhitehouse.archives.gov/blog/author/brian-levine",
        "https://obamawhitehouse.archives.gov/blog/author/broderick-johnson",
        "https://obamawhitehouse.archives.gov/blog/author/carrie-bettinger-lopez",
        "https://obamawhitehouse.archives.gov/blog/author/cecilia-mu%C3%B1oz",
        "https://obamawhitehouse.archives.gov/blog/author/charlie-anderson",
        "https://obamawhitehouse.archives.gov/blog/author/colleen-curtis",
        "https://obamawhitehouse.archives.gov/blog/author/craig-fugate",
        "https://obamawhitehouse.archives.gov/blog/author/dan-utech",
        "https://obamawhitehouse.archives.gov/blog/author/danny-werfel",
        "https://obamawhitehouse.archives.gov/blog/author/david-vandivier",
        "https://obamawhitehouse.archives.gov/blog/author/david-wilkinson",
        "https://obamawhitehouse.archives.gov/blog/author/derek-douglas",
        "https://obamawhitehouse.archives.gov/blog/author/dj-patil",
        "https://obamawhitehouse.archives.gov/blog/author/doug-rand",
        "https://obamawhitehouse.archives.gov/blog/author/dr-jill-biden",
        "https://obamawhitehouse.archives.gov/blog/author/elizabeth-alexander",
        "https://obamawhitehouse.archives.gov/blog/author/eric-waldo",
        "https://obamawhitehouse.archives.gov/blog/author/felicia-escobar",
        "https://obamawhitehouse.archives.gov/blog/author/first-lady-michelle-obama",
        "https://obamawhitehouse.archives.gov/blog/author/gayle-smith",
        "https://obamawhitehouse.archives.gov/blog/author/gina-mccarthy",
        "https://obamawhitehouse.archives.gov/blog/author/grant-t-harris",
        "https://obamawhitehouse.archives.gov/blog/author/greg-nelson",
        "https://obamawhitehouse.archives.gov/blog/author/hope-hall",
        "https://obamawhitehouse.archives.gov/blog/author/howard-schmidt",
        "https://obamawhitehouse.archives.gov/blog/author/jack-lew",
        "https://obamawhitehouse.archives.gov/blog/author/jared-bernstein",
        "https://obamawhitehouse.archives.gov/blog/author/jason-furman",
        "https://obamawhitehouse.archives.gov/blog/author/jeffrey-zients",
        "https://obamawhitehouse.archives.gov/blog/author/jennifer-erickson",
        "https://obamawhitehouse.archives.gov/blog/author/jennifer-palmieri",
        "https://obamawhitehouse.archives.gov/blog/author/jerry-abramson",
        "https://obamawhitehouse.archives.gov/blog/author/jesse-lee",
        "https://obamawhitehouse.archives.gov/blog/author/joshua-miller",
        "https://obamawhitehouse.archives.gov/blog/author/julie-chavez-rodriguez",
        "https://obamawhitehouse.archives.gov/blog/author/kori-schulman",
        "https://obamawhitehouse.archives.gov/blog/author/kristin-lee",
        "https://obamawhitehouse.archives.gov/blog/author/kyle-lierman",
        "https://obamawhitehouse.archives.gov/blog/author/laura-miller",
        "https://obamawhitehouse.archives.gov/blog/author/lauren-kelly",
        "https://obamawhitehouse.archives.gov/blog/author/lindsay-holst",
        "https://obamawhitehouse.archives.gov/blog/author/lisa-o-monaco",
        "https://obamawhitehouse.archives.gov/blog/author/liz-oxhorn",
        "https://obamawhitehouse.archives.gov/blog/author/lloyd-whitman",
        "https://obamawhitehouse.archives.gov/blog/author/macon-phillips",
        "https://obamawhitehouse.archives.gov/blog/author/matt-compton",
        "https://obamawhitehouse.archives.gov/blog/author/maureen-tracey-mooney",
        "https://obamawhitehouse.archives.gov/blog/author/megan-slack",
        "https://obamawhitehouse.archives.gov/blog/author/megan-smith",
        "https://obamawhitehouse.archives.gov/blog/author/michael-botticelli",
        "https://obamawhitehouse.archives.gov/blog/author/monique-dorsainvil",
        "https://obamawhitehouse.archives.gov/blog/author/pete-souza",
        "https://obamawhitehouse.archives.gov/blog/author/president-barack-obama",
        "https://obamawhitehouse.archives.gov/blog/author/r-david-edelman",
        "https://obamawhitehouse.archives.gov/blog/author/rachel-kopilow",
        "https://obamawhitehouse.archives.gov/blog/author/rick-weiss",
        "https://obamawhitehouse.archives.gov/blog/author/roberto-j-rodr%C3%ADguez",
        "https://obamawhitehouse.archives.gov/blog/author/samantha-power",
        "https://obamawhitehouse.archives.gov/blog/author/secretary-anthony-foxx",
        "https://obamawhitehouse.archives.gov/blog/author/secretary-arne-duncan",
        "https://obamawhitehouse.archives.gov/blog/author/secretary-ernest-moniz",
        "https://obamawhitehouse.archives.gov/blog/author/secretary-penny-pritzker",
        "https://obamawhitehouse.archives.gov/blog/author/secretary-ray-lahood",
        "https://obamawhitehouse.archives.gov/blog/author/secretary-steven-chu",
        "https://obamawhitehouse.archives.gov/blog/author/secretary-sylvia-mathews-burwell",
        "https://obamawhitehouse.archives.gov/blog/author/secretary-thomas-e-perez",
        "https://obamawhitehouse.archives.gov/blog/author/secretary-tom-vilsack",
        "https://obamawhitehouse.archives.gov/blog/author/simone-leiro",
        "https://obamawhitehouse.archives.gov/blog/author/steve-vanroekel",
        "https://obamawhitehouse.archives.gov/blog/author/terrell-mcsweeny",
        "https://obamawhitehouse.archives.gov/blog/author/thomas-kalil",
        "https://obamawhitehouse.archives.gov/blog/author/tobin-marcus",
        "https://obamawhitehouse.archives.gov/blog/author/todd-park",
        "https://obamawhitehouse.archives.gov/blog/author/valerie-jarrett",
        "https://obamawhitehouse.archives.gov/blog/author/victoria-espinel",
        "https://obamawhitehouse.archives.gov/champions/blog",
        "https://obamawhitehouse.archives.gov/economy/business/startup-america",
        "https://obamawhitehouse.archives.gov/economy/business/startup-america/commitments",
        "https://obamawhitehouse.archives.gov/economy/business/startup-america/contact",
        "https://obamawhitehouse.archives.gov/economy/business/startup-america/progress-report",
        "https://obamawhitehouse.archives.gov/economy/jobs/news",
        "https://obamawhitehouse.archives.gov/economy/jobsact",
        "https://obamawhitehouse.archives.gov/goodgovernment/news",
        "https://obamawhitehouse.archives.gov/issues/education/k-12/connected",
        "https://obamawhitehouse.archives.gov/issues/education/k-12/race-to-the-top",
        "https://obamawhitehouse.archives.gov/jobsact/read-the-bill",
        "https://obamawhitehouse.archives.gov/joiningforces/blog",
        "https://obamawhitehouse.archives.gov/omb/blog",
        "https://obamawhitehouse.archives.gov/ondcp/blog",
        "https://obamawhitehouse.archives.gov/open/blog",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/archives-first-families-celebrate-holidays-white-house",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/archives-first-pets-celebrate-holidays-white-house",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/august-2016-photo-day",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/december-2016-photo-day",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/holidays-white-house",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/january-2017-photo-day",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/july-2016-photo-day",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/june-2016-photo-day",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/november-2016-photo-day",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/october-2016-photo-day",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/scenes-first-ladys-past-commencement-addresses",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/september-2016-photo-day",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/vice-president-and-dr-biden-middle-east",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/vice-president-and-dr-bidens-trip-india-and-singapore",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/vice-president-biden-spain-and-belgium-1",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/vice-president-biden-visits-afghanistan-pakistan-and-iraq",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/vice-president-joe-biden-tk",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/vice-president-joe-biden-turkey/index__q_category=30.html",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/vice-presidents-trip-asia",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2009/12/22/gingerbread-white-house",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2010/12/08/open-questions-first-anniversary-open-government-directive",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2011/06/13/building-21st-century-grid",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2011/12/21/pcast-december-conference-call",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2012/03/27/president-obama-speaks-nuclear-security-summit",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2012/04/26/pcast-april-conference-call",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2013/05/09/president-obama-speaks-innovation-and-manufacturing",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2013/05/09/president-obama-speaks-manor-new-technology-high-school",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2013/06/06/google-hangout-national-show-and-tell-connected-classrooms",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2013/06/06/president-obama-speaks-technology-schools",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2013/12/05/president-obama-speaks-afternoon-hanukkah-reception",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2013/12/05/president-obama-speaks-evening-hanukkah-reception",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2013/12/13/west-wing-week-121313-or-madiba-farewell",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2013/12/18/board-travels-vice-president-asia",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2013/12/22/west-wing-week-122413-or-west-wing-week-holiday-card",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2013/12/25/weekly-address-president-and-first-lady-wish-everyone-happy-holida",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2014/02/04/president-obama-speaks-connected",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2014/07/08/road-drc-dr-mukwege-panzi-hospital",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2014/07/19/equipping-workers-skills-employers-need-now-and-future",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2014/07/23/white-house-white-board-vice-president-biden-rebuild-america",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2014/08/20/introducing-us-digital-service",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2014/11/14/west-wing-week-111414-or-future-we-see",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2015/01/28/board-kal-penn-travels-president-obama-india",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2015/02/13/president-obama-speaks-cybersecurity-and-consumer-protection-summi",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2015/02/18/president-obama-speaks-summit-countering-violent-extremism",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2015/02/19/president-obama-speaks-summit-countering-violent-extremism",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2015/03/23/president-obama-delivers-message-nigerian-people",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2015/04/17/tech-meetup-white-house",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2015/05/08/west-wing-week-05082015-or-viva-los-estados-unidos",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2015/05/18/president-speaks-youth-and-law-enforcement-new-jersey",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2015/05/22/west-wing-week-05222015-or-potus",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2015/08/15/continuing-work-improve-community-policing",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2015/12/06/president-addresses-nation-keeping-american-people-safe",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2015/12/17/president-speaks-national-counterterrorism-center",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2016/04/01/potus-nuclear-security-summit-press-conference",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2016/04/01/president-obama-chairs-closing-session-nuclear-summit",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2016/04/01/president-obama-meets-members-p5-plus-1",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2016/06/13/white-house-organ-summit",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2016/09/08/first-lady-michelle-obama-honors-2016-class-national-student-poets",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2016/09/21/president-obama-delivers-remarks-us-africa-business-forum",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2016/10/17/president-obama-delivers-remarks-education",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2016/12/21/white-house-summit-building-tech-workforce-tomorrow",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2017/01/12/organizational-transformation-symposium",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2017/01/13/11317-white-house-press-briefing",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2017/01/13/healthy-campus-challenge-day-white-house",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2017/01/14/weekly-address-honor-serving-you-president",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2017/01/16/2016-world-series-champion-chicago-cubs",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2017/01/16/participating-service-project-martin-luther-king-jr-day",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2017/01/17/11717-white-house-press-briefing",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/forum-modernizing-government-closing-session",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/forum-modernizing-government-maximizing-technology-return-investment",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/forum-modernizing-government-opening-session",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/forum-modernizing-government-streamlining-operations-1",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/forum-modernizing-government-streamlining-operations-2",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/forum-modernizing-government-transforming-customer-service-1",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/forum-modernizing-government-transforming-customer-service-2",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/limiting-influence-special-interests",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/open-questions-sustainable-communities",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/recovery-act-tax-savings-tool",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/tax-accountability-government-contracts",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/vice-president-biden-speaks-kenya",
        "https://obamawhitehouse.archives.gov/recovery/blog",
        "https://obamawhitehouse.archives.gov/strongmiddleclass/blog",
        "https://obamawhitehouse.archives.gov/video/President-Obama-Speaks-to-the-Muslim-World-from-Cairo-Egypt",
        "https://obamawhitehouse.archives.gov/video/President-Obama-on-Urban-Policy",
        # Discovered via the nav harvester run 5 (DEPTH_LIMIT=12, tightened
        # is_listing check), reviewed and confirmed as real listings.
        # Excluded from promotion: 3 congress.gov-linked legislation listings
        # (external content, not indexable via this spider), 3 redundant old
        # /video/ URL aliases (identical items to an already-covered gallery),
        # /blog/authors (0 items under current selectors - different markup,
        # not yet walkable), and one redundant pagination artifact of an
        # already-listed root.
        "https://obamawhitehouse.archives.gov/1is2many/blog",
        "https://obamawhitehouse.archives.gov/administration/eop/aapi/blog",
        "https://obamawhitehouse.archives.gov/administration/eop/dpc/blog",
        "https://obamawhitehouse.archives.gov/administration/eop/nec/blog",
        "https://obamawhitehouse.archives.gov/administration/eop/nsc/blog",
        "https://obamawhitehouse.archives.gov/administration/eop/nsc/press",
        "https://obamawhitehouse.archives.gov/administration/eop/oceans/whats-new",
        "https://obamawhitehouse.archives.gov/administration/eop/rural-council/blog",
        "https://obamawhitehouse.archives.gov/administration/eop/rural-council/policy-initiatives",
        "https://obamawhitehouse.archives.gov/administration/eop/rural-council/press",
        "https://obamawhitehouse.archives.gov/administration/eop/rural-council/rural-blog-posts",
        "https://obamawhitehouse.archives.gov/africanamericans/blog",
        "https://obamawhitehouse.archives.gov/africanamericans/press",
        "https://obamawhitehouse.archives.gov/arabamericans/blog",
        "https://obamawhitehouse.archives.gov/blog/author/alan-krueger",
        "https://obamawhitehouse.archives.gov/blog/author/alejandra-campoverdi",
        "https://obamawhitehouse.archives.gov/blog/author/alex-wall",
        "https://obamawhitehouse.archives.gov/blog/author/amanda-stone",
        "https://obamawhitehouse.archives.gov/blog/author/ambassador-ron-kirk",
        "https://obamawhitehouse.archives.gov/blog/author/ambassador-susan-rice",
        "https://obamawhitehouse.archives.gov/blog/author/amy-lansky",
        "https://obamawhitehouse.archives.gov/blog/author/ari-matusiak",
        "https://obamawhitehouse.archives.gov/blog/author/ashleigh-axios",
        "https://obamawhitehouse.archives.gov/blog/author/austan-goolsbee",
        "https://obamawhitehouse.archives.gov/blog/author/betsey-stevenson",
        "https://obamawhitehouse.archives.gov/blog/author/brad-cooper",
        "https://obamawhitehouse.archives.gov/blog/author/cameron-brenchley",
        "https://obamawhitehouse.archives.gov/blog/author/cass-sunstein",
        "https://obamawhitehouse.archives.gov/blog/author/dan-pfeiffer",
        "https://obamawhitehouse.archives.gov/blog/author/david-hudson",
        "https://obamawhitehouse.archives.gov/blog/author/dr-tamara-dickinson",
        "https://obamawhitehouse.archives.gov/blog/author/elizabeth-warren",
        "https://obamawhitehouse.archives.gov/blog/author/erin-lindsay",
        "https://obamawhitehouse.archives.gov/blog/author/ezra-mechaber",
        "https://obamawhitehouse.archives.gov/blog/author/gautam-raghavan",
        "https://obamawhitehouse.archives.gov/blog/author/gene-sperling",
        "https://obamawhitehouse.archives.gov/blog/author/heather-zichal",
        "https://obamawhitehouse.archives.gov/blog/author/jen-psaki",
        "https://obamawhitehouse.archives.gov/blog/author/jenna-brayton",
        "https://obamawhitehouse.archives.gov/blog/author/john-podesta",
        "https://obamawhitehouse.archives.gov/blog/author/jon-carson",
        "https://obamawhitehouse.archives.gov/blog/author/jonathan-greenblatt",
        "https://obamawhitehouse.archives.gov/blog/author/josh-earnest",
        "https://obamawhitehouse.archives.gov/blog/author/joshua-dubois",
        "https://obamawhitehouse.archives.gov/blog/author/kalpen-modi",
        "https://obamawhitehouse.archives.gov/blog/author/karen-mills",
        "https://obamawhitehouse.archives.gov/blog/author/kasie-coccaro",
        "https://obamawhitehouse.archives.gov/blog/author/katelyn-sabochik",
        "https://obamawhitehouse.archives.gov/blog/author/katherine-vargas",
        "https://obamawhitehouse.archives.gov/blog/author/ken-meyer",
        "https://obamawhitehouse.archives.gov/blog/author/ken-salazar",
        "https://obamawhitehouse.archives.gov/blog/author/kumar-garg",
        "https://obamawhitehouse.archives.gov/blog/author/luis-miranda",
        "https://obamawhitehouse.archives.gov/blog/author/lynn-rosenthal",
        "https://obamawhitehouse.archives.gov/blog/author/matt-flavin",
        "https://obamawhitehouse.archives.gov/blog/author/matt-nosanchuk",
        "https://obamawhitehouse.archives.gov/blog/author/max-sgro",
        "https://obamawhitehouse.archives.gov/blog/author/melanie-garunay",
        "https://obamawhitehouse.archives.gov/blog/author/melody-barnes",
        "https://obamawhitehouse.archives.gov/blog/author/michael-daniel",
        "https://obamawhitehouse.archives.gov/blog/author/nancy-ann-deparle",
        "https://obamawhitehouse.archives.gov/blog/author/nancy-sutley",
        "https://obamawhitehouse.archives.gov/blog/author/nathaniel-lubin",
        "https://obamawhitehouse.archives.gov/blog/author/nikki-sutton",
        "https://obamawhitehouse.archives.gov/blog/author/peter-orszag",
        "https://obamawhitehouse.archives.gov/blog/author/peter-welsch",
        "https://obamawhitehouse.archives.gov/blog/author/ronnie-cho",
        "https://obamawhitehouse.archives.gov/blog/author/sam-kass",
        "https://obamawhitehouse.archives.gov/blog/author/secretary-hilda-solis",
        "https://obamawhitehouse.archives.gov/blog/author/secretary-juli%C3%A1n-castro",
        "https://obamawhitehouse.archives.gov/blog/author/secretary-kathleen-sebelius",
        "https://obamawhitehouse.archives.gov/blog/author/secretary-sally-jewell",
        "https://obamawhitehouse.archives.gov/blog/author/stephanie-cutter",
        "https://obamawhitehouse.archives.gov/blog/author/stephanie-valencia",
        "https://obamawhitehouse.archives.gov/blog/author/stub",
        "https://obamawhitehouse.archives.gov/blog/author/tanya-somanader",
        "https://obamawhitehouse.archives.gov/blog/author/tina-tchen",
        "https://obamawhitehouse.archives.gov/blog/ladders-of-opportunity",
        "https://obamawhitehouse.archives.gov/briefing-room/presidential-actions/executive-orders",
        "https://obamawhitehouse.archives.gov/briefing-room/presidential-actions/presidential-memoranda",
        "https://obamawhitehouse.archives.gov/briefing-room/presidential-actions/proclamations",
        "https://obamawhitehouse.archives.gov/energy/news",
        "https://obamawhitehouse.archives.gov/featured-videos",
        "https://obamawhitehouse.archives.gov/healthreform/blog",
        "https://obamawhitehouse.archives.gov/healthreform/press",
        "https://obamawhitehouse.archives.gov/hispanic/blog",
        "https://obamawhitehouse.archives.gov/jewishamericans/blog",
        "https://obamawhitehouse.archives.gov/letters",
        "https://obamawhitehouse.archives.gov/lgbt/blog",
        "https://obamawhitehouse.archives.gov/nativeamericans/blog",
        "https://obamawhitehouse.archives.gov/ondcp/news-releases",
        "https://obamawhitehouse.archives.gov/ondcp/speeches",
        "https://obamawhitehouse.archives.gov/photos",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/2011-state-union",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/2012-state-union-address",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/2013-state-union-address",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/2014-2015-white-house-fellows",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/2014-state-union-address",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/40-dollars-50-states-1",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/dr-biden-and-secretary-solis-hit-road-community-college-career-tour",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/first-lady-michelle-obama-and-dr-jill-biden-visit-fort-campbell",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/first-ladys-2011-trip-south-africa-and-botswana",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/g20-summit-los-cabos-mexico",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/g8-summit-camp-david",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/hillary-clinton-winter-wonderland",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/hud-secretary-shaun-donovan-visits-new-jersey-communities-impacted-hur",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/inauguration-president-barack-obama-and-vice-president-joe-biden",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/laura-bush-red-white-and-blue",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/made-america-what-exports-mean-american-economy",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/michelle-obama-joy-all",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/middle-class-task-force-meeting-philadelphia",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/middle-east-trip-blog-post-photo-gallery",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/new-start-treaty",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/president-barack-obama-tours-storm-damage-new-jersey",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/president-barack-obama-tours-storm-damage-new-york",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/president-obama-designates-five-new-national-monuments",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/president-trip-israel-west-bank-and-jordan",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/presidents-trip-israel-west-bank-and-jordan",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/thanksgiving-presidents",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/title-ix-action",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/us-africa-leaders-summit",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/vice-president-joe-biden-tours-new-jersey-after-hurricane-sandy",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/white-house-easter-egg-roll-american-tradition-1878",
        "https://obamawhitehouse.archives.gov/photos-and-video/photogallery/working-towards-middle-east-peace",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2010-presidential-citizen-s-medal",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2010/09/01/middle-east-peace-talks",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2010/09/16/expanding-educate-innovate",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2010/11/02/tuesday-talks-president-s-foreign-trip",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2010/11/16/medal-honor-staff-sergeant-salvatore-giunta",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2010/12/06/education-innovation-economy",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2010/12/13/signing-healthy-hunger-free-kids-act",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2011/01/08/president-obama-arizona-attack-and-rep-giffords",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2011/01/10/moment-silence-arizona-shooting-victims",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2011/01/27/open-questions-state-union-and-economy",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2011/01/27/open-questions-state-union-and-education",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2011/01/27/open-questions-state-union-and-foreign-policy",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2011/01/27/open-questions-state-union-and-health-care",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2011/01/31/startup-america",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2011/02/08/building-21st-century-infrastructure",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2011/02/16/president-obama-americas-great-outdoors-initiative",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2011/02/22/winning-future-forum-small-business-closing-session",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2011/03/10/president-obama-first-lady-address-bullying",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2011/03/10/president-obama-first-lady-conference-bullying-prevention",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2011/04/12/first-lady-michelle-obama-and-dr-jill-biden-launch-joining-forces",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2011/05/10/building-21st-century-immigration-system",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2011/06/16/first-ladys-trip-africa",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2011/06/22/board-first-day-first-lady-south-africa",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2011/06/22/first-family-reads-cat-hat",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2011/06/22/raw-video-first-lady-visits-emthonjeni-community-center-0",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2011/06/24/board-first-lady-speaks-about-meeting-nelson-mandela",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2011/06/24/raw-video-first-lady-michelle-obama-desmond-tutu-do-push-ups",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2011/06/27/board-first-lady-michelle-obama-visits-baylor-center",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2011/07/08/travels-first-lady-africa",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2011/07/15/west-wing-week-71411-or-our-heroes-are-all-around-us",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2011/09/08/open-questions-american-jobs-act",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2011/09/08/president-obama-presents-american-jobs-act-enhanced-version",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2011/09/16/secretary-education-arne-duncan-announces-launch-digital-promise",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2011/09/23/president-obama-no-child-left-behind-flexibility",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2011/09/26/first-lady-michelle-obama-national-science-foundation-family-frien",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2011/10/07/white-house-google-global-science-fair-winners",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2011/10/11/breast-cancer-awareness-access-care",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2011/10/20/president-obama-presents-2011-presidential-citizens-medals",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2011/10/21/advice-young-women-interested-science",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2011/11/01/vice-president-biden-delivers-remarks-london-conference-cyberspace",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2011/12/02/president-obama-and-president-clinton-speak-better-building-initia",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2012/01/23/we-cant-wait",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2012/01/25/2012-state-union-address-enhanced-version",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2012/02/07/marshmallow-launch-white-house-science-fair",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2012/02/07/president-obama-speaks-white-house-science-fair",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2012/03/02/president-obama-speaks-conference-conservation",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2012/03/14/uk-official-visit-arrival-ceremony",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2012/04/06/president-obama-speaks-white-house-forum-women-and-economy",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2012/04/24/girls-stem-new-generation-women-and-science",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2012/05/19/president-obama-speaks-food-security-g8-meeting",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2012/06/20/title-ix-40",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2012/07/25/president-obama-speaks-national-urban-league-convention",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2012/08/22/joining-forces-provide-jobs-military-families",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2012/09/25/president-obama-speaks-clinton-global-initiative-annual-meeting",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2012/10/31/president-obama-tours-areas-damaged-hurricane-sandy",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2012/11/22/west-wing-week-112212-or-hello-burma",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2012/12/11/president-obamas-message-global-entrepreneurship-summit",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2013/01/16/president-obama-introduces-plan-reduce-gun-violence",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2013/02/07/president-obama-speaks-national-prayer-breakfast",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2013/02/14/president-obama-early-childhood-education",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2013/02/15/president-obama-presents-2012-presidential-citizens-medals",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2013/02/15/president-obama-speaks-strengthening-economy-middle-class",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2013/02/25/first-lady-and-dr-biden-speak-national-governors-association",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2013/03/20/president-obama-speaks-arrival-ceremony-israel",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2013/03/20/president-obamas-meeting-president-peres-israel",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2013/03/27/healthy-game-day-meals-la-kings-la-galaxy",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2013/04/02/president-obama-speaks-brain-initiative-and-american-innovation",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2013/05/03/president-obama-speaks-people-mexico",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2013/06/10/rhodes-sunnylands-summit",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2013/06/13/lgbt-pride-month-reception-white-house",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2013/06/17/president-obama-speaks-people-northern-ireland",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2013/06/17/previewing-presidents-trip-northern-ireland-germany",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2013/06/25/president-obama-speaks-climate-change",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2013/06/29/weekly-address-confronting-growing-threat-climate-change",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2013/07/05/west-wing-week-070513-or-dispatches-africa",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2013/08/02/around-world-vice-president-dr-biden",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2013/09/04/president-obama-honors-raoul-wallenberg",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2013/09/05/president-obamas-bilateral-meeting-prime-minister-abe-japan",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2013/09/05/west-wing-week-090613-or-stronger-together",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2013/09/14/weekly-address-pursuing-diplomatic-solution-syria",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2013/09/27/white-house-white-board-what-obamacare-means-you",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2013/10/10/president-obamas-message-4th-annual-global-entrepreneurship-summit",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2014/01/16/west-wing-week-11714-or-give-peace-chance",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2014/01/22/president-and-vice-president-speak-preventing-sexual-assault",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2014/02/21/west-wing-week-22114-or-dont-make-small-plans-make-big-plans",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2014/03/11/president-obama-designates-point-arena-stornetta-public-lands-nati",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2014/04/25/west-wing-week-042514-or-potus-dreams-sushi-0",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2014/04/28/president-obama-speaks-new-commercial-agreements-malaysia",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2014/04/29/president-obama-speaks-port-bonifacio",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2014/05/09/inside-white-house-solar-panels",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2014/05/09/president-obama-speaks-american-energy",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2014/05/30/my-brothers-keeper-initiative",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2014/06/06/president-obama-commemorates-70th-anniversary-d-day",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2014/06/16/highlights-president-obama-visits-standing-rock-reservation-north-",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2014/07/04/president-speaks-naturalization-ceremony",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2014/07/22/president-signs-workforce-innovation-and-opportunity-act",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2014/09/02/president-obama-delivers-message-west-africans-ebola",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2014/09/03/president-obama-addresses-people-estonia",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2014/09/03/president-obama-and-prime-minister-roivas-estonia-address-servicem",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2014/09/03/presidents-us-estonia-latvia-and-lithuania-deliver-remarks",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2014/09/26/president-delivers-remarks-global-health-security-agenda-summit",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2014/09/27/president-addresses-congressional-black-caucus",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2014/10/10/president-obama-designates-san-gabriel-mountains-national-monument",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2014/10/10/white-house-whiteboard-shorts-raisethewage",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2014/10/24/digital-briefing-ebola",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2014/10/29/president-obama-delivers-remarks-american-health-care-workers-figh",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2014/11/18/president-obama-provides-update-us-response-ebola",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2014/11/21/behind-scenes-video-100-minutes-countdown-presidential-address",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2014/12/02/president-obama-speaks-fight-against-ebola",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2014/12/17/president-obama-speaks-hanukkah-reception",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2014/12/29/west-wing-week-1215-or-zingy-sting-special-year-end-edition",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2015/03/09/president-obama-speaks-national-league-cities-conference",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2015/03/17/white-house-open-government-workshop",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2015/03/23/president-obama-tours-2015-white-house-science-fair-exhibits",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2015/04/14/first-lady-speaks-history-gospel-music-workshop",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2015/04/17/west-wing-week-041715-or-quintessential-sounds",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2015/04/27/catching-curator-obama-state-china-service",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2015/05/15/west-wing-week-05152015-or-50th-state",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2015/05/21/president-obama-meets-president-tunisia",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2015/05/21/president-speaks-meeting-his-cabinet",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2015/05/28/west-wing-week-052915-or-high-fives-everybody",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2015/06/06/weekly-address-celebrating-immigrant-heritage-month",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2015/06/11/first-lady-speaks-king-college-prep-high-schools-commencement",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2015/06/19/president-speaks-annual-meeting-us-conference-mayors",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2015/07/16/president-obama-visits-el-reno-federal-correctional-institution",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2015/07/31/president-signs-extension-highway-funding-bill",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2015/08/03/president-speaks-yali-2015-summit",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2015/08/04/president-obama-meets-un-secretary-general-ban-ki-moon",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2015/08/05/president-speaks-iran-nuclear-deal-american-university",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2015/08/07/west-wing-week-080715-or-measure-leader",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2015/09/12/weekly-addresss-new-college-scorecard",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2015/09/14/president-speaks-college-access-and-affordability",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2016/01/29/weekly-address-giving-every-student-opportunity-learn-through-comp",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2016/03/11/president-obama-participates-south-southwest-interactive-discussio",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2016/04/01/david-cameron-fran-ois-hollande-reflect-nuclear-security-summit-ma",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2016/04/21/president-obama-and-king-salman-deliver-statements-press",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2016/04/21/president-obama-speaks-press",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2016/04/24/president-obama-speaks-hannover-messe-trade-fair",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2016/04/25/president-obama-delivers-remarks-hannover-messe-building-35",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2016/04/25/president-obama-speaks-hannover-messe-trade-fair",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2016/05/05/president-obama-hosts-cinco-de-mayo-reception",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2016/05/27/president-obama-participates-wreath-laying-ceremony",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2016/06/29/president-obama-addresses-parliament",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2016/06/29/president-obama-and-president-nieto",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2016/06/29/president-obama-participates-trilateral-press-conference",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2016/06/29/vice-president-biden-delivers-remarks-cancer-moonshot-summit-closi",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2016/08/24/announcing-katahdin-woods-and-waters-national-monument",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2016/09/01/president-obama-delivers-statement-press",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2016/09/06/president-obama-and-president-park",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2016/09/06/white-house-press-briefing",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2016/11/11/remarks-veterans-day-ceremony",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/2016/11/18/convening-diversity-inclusion-higher-ed",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/climate-change-adaptation-task-force-outreach-meeting-oregon",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/climate-change-task-force-hawaii",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/creating-new-jobs-a-clean-energy-economy",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/dr-jill-biden-good-news-higher-education",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/haiti-earthquake-relief-update",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/inside-white-house-bees",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/new-recovery-act-investments-health-it",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/open-questions-innovation-2011-budget",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/open-questions-national-export-initiative",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/open-questions-year-changing-washington",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/president-obama-commemorates-enactment-hate-crimes-prevention-act",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/president-obama-explains-healthcaregov",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/president-obama-kicks-educate-innovate",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/president-obama-pardons-white-house-turkey",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/president-obama-presents-a-night-astronomy",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/president-obama-signs-health-reform-law",
        "https://obamawhitehouse.archives.gov/photos-and-video/video/white-house-easter-prayer-breakfast",
        "https://obamawhitehouse.archives.gov/youngafrica/blog",
        "https://obamawhitehouse.archives.gov/youngamericans/blog",
        # Found via /blog/authors (a person-directory listing of every blog
        # author - NOT itself added here, see the note above parse() for
        # why) - these 42 author blogs were never surfaced by nav wandering
        # at all, only by walking that directory's own pagination as a
        # one-off discovery pass.
        "https://obamawhitehouse.archives.gov/blog/author/Tania-Simoncelli",
        "https://obamawhitehouse.archives.gov/blog/author/alefiyah-mesiwala",
        "https://obamawhitehouse.archives.gov/blog/author/alissa-ko",
        "https://obamawhitehouse.archives.gov/blog/author/amanda-lucidon",
        "https://obamawhitehouse.archives.gov/blog/author/anita-breckenridge",
        "https://obamawhitehouse.archives.gov/blog/author/asra-najam",
        "https://obamawhitehouse.archives.gov/blog/author/bess-evans",
        "https://obamawhitehouse.archives.gov/blog/author/brian-mosteller",
        "https://obamawhitehouse.archives.gov/blog/author/candace-vahlsing",
        "https://obamawhitehouse.archives.gov/blog/author/cassandra-marketos",
        "https://obamawhitehouse.archives.gov/blog/author/christine-harada-0",
        "https://obamawhitehouse.archives.gov/blog/author/christy-goldfuss",
        "https://obamawhitehouse.archives.gov/blog/author/contessa-jin",
        "https://obamawhitehouse.archives.gov/blog/author/cristin-dorgelo",
        "https://obamawhitehouse.archives.gov/blog/author/david-simas",
        "https://obamawhitehouse.archives.gov/blog/author/denis-mcdonough",
        "https://obamawhitehouse.archives.gov/blog/author/fred-p-hochberg",
        "https://obamawhitehouse.archives.gov/blog/author/ginette-maga%C3%B1a",
        "https://obamawhitehouse.archives.gov/blog/author/jamal-brown",
        "https://obamawhitehouse.archives.gov/blog/author/jason-goldman",
        "https://obamawhitehouse.archives.gov/blog/author/jennifer-lee",
        "https://obamawhitehouse.archives.gov/blog/author/jesse-moore",
        "https://obamawhitehouse.archives.gov/blog/author/jillian-maryonovich",
        "https://obamawhitehouse.archives.gov/blog/author/john-p-holdren",
        "https://obamawhitehouse.archives.gov/blog/author/katy-kale",
        "https://obamawhitehouse.archives.gov/blog/author/keith-maley",
        "https://obamawhitehouse.archives.gov/blog/author/kimberlyn-leary",
        "https://obamawhitehouse.archives.gov/blog/author/laura-s-h-holgate",
        "https://obamawhitehouse.archives.gov/blog/author/maya-shankar",
        "https://obamawhitehouse.archives.gov/blog/author/michael-d-smith",
        "https://obamawhitehouse.archives.gov/blog/author/michael-robertson",
        "https://obamawhitehouse.archives.gov/blog/author/parker-liautaud",
        "https://obamawhitehouse.archives.gov/blog/author/paulette-aniskoff",
        "https://obamawhitehouse.archives.gov/blog/author/rohan-patel",
        "https://obamawhitehouse.archives.gov/blog/author/secretary-ashton-carter",
        "https://obamawhitehouse.archives.gov/blog/author/secretary-john-kerry",
        "https://obamawhitehouse.archives.gov/blog/author/sheila-nix",
        "https://obamawhitehouse.archives.gov/blog/author/vice-president-joe-biden",
        "https://obamawhitehouse.archives.gov/blog/author/yohannes-abraham",
    ]

    # /blog/authors is a person-directory listing (view-person-listings) of
    # every blog author - deliberately NOT in start_urls above, even though
    # parse() below can now extract it via .views-field-nid. Its "items" are
    # themselves listing pages (/blog/author/X), not content - walking it
    # normally would yield listing-page URLs into harvest-listing.csv as if
    # they were leaf content, the same mistake made and corrected earlier
    # this session (see NavHarvesterMixin's listing_file docstring). Confirmed
    # via a one-off discovery pass (not a start_urls entry) that its 110
    # entries include 42 author blogs not otherwise in start_urls - those 42
    # are listed above individually instead.

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Spans the whole run, not just one seed's own pagination walk: some
        # listing templates embed the *same* underlying view on every page in
        # the set rather than one scoped to that specific page, so two
        # different start_urls can walk into an identical, already-known item
        # range. Confirmed empirically: every /photos-and-video/video/*
        # permalink embeds the same sitewide "latest videos" catalog (not a
        # per-video "related content" widget - two different videos' pages
        # showed byte-identical item lists), so without this, ~30 separate
        # video-permalink seeds would each independently re-walk the same
        # 740-page catalog.
        self._seen_urls = set()

    def parse(self, response):
        # Three known listing templates: teaser-card (.views-row h2/h3 a,
        # e.g. blog/author pages), table-based gallery (.views-field-title,
        # e.g. photo/video galleries), and person-directory
        # (.views-field-nid, e.g. /blog/authors - see the note above this
        # method for why that specific page isn't walked as a normal seed
        # despite this selector supporting it). Try each in turn.
        links = response.css(
            '.views-row h2 a::attr(href), .views-row h3 a::attr(href)'
        ).getall()
        if not links:
            links = response.css('.views-field-title a::attr(href)').getall()
        if not links:
            links = response.css('.views-row .views-field-nid a::attr(href)').getall()
        if not links:
            return

        new_count = 0
        for href in links:
            url = response.urljoin(href)
            if url in self._seen_urls:
                continue
            self._seen_urls.add(url)
            new_count += 1
            yield {'url': url}

        # .pager-current's immediately-following sibling <li> holds the
        # forward link in both templates (a "Next" link in the teaser-card
        # pager, a numbered page link in the gallery pager) - confirmed
        # empirically on both, so one selector covers both rather than
        # branching on .pager-next (which the gallery template doesn't use
        # at all).
        #
        # Stop paginating once a page yields zero new items: a shared view
        # (see _seen_urls above) is confirmed deterministic and identical
        # regardless of entry point, so once a seed has walked into a range
        # another seed already fully covered, every further page will also
        # be 100% duplicate - continuing would just re-fetch the rest of
        # that other seed's own walk for no new content.
        next_page = response.css('.pager-current + li a::attr(href)').get()
        if next_page and new_count > 0:
            yield response.follow(next_page, callback=self.parse)
